export const ALL_NESTED_CATEGORY_REQUEST = 'ALL_NESTED_CATEGORY_REQUEST'
export const ALL_NESTED_CATEGORY_SUCCESS = 'ALL_NESTED_CATEGORY_SUCCESS'
export const ALL_NESTED_CATEGORY_FAIL = 'ALL_NESTED_CATEGORY_FAIL'



export const FLASH_SALE_REQUEST = 'FLASH_SALE_REQUEST'
export const FLASH_SALE_SUCCESS = 'FLASH_SALE_SUCCESS'
export const FLASH_SALE_FAIL = 'FLASH_SALE_FAIL'


export const TOP_CATEGORY_REQUEST = 'TOP_CATEGORY_REQUEST'
export const TOP_CATEGORY_SUCCESS = 'TOP_CATEGORY_SUCCESS'
export const TOP_CATEGORY_FAIL = 'TOP_CATEGORY_FAIL'


export const DASH_PRODUCT_REQUEST = "DASH_PRODUCT_REQUEST"
export const DASH_PRODUCT_SUCCESS = "DASH_PRODUCT_SUCCESS"
export const DASH_PRODUCT_FAIL = "DASH_PRODUCT_FAIL"

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST"
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS"
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL"